
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './database.types';

const SUPABASE_URL = "https://rvmmbylrjtuqrnojzpua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2bW1ieWxyanR1cXJub2p6cHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzY0OTEsImV4cCI6MjA1OTM1MjQ5MX0.f8P13qb6bX5Bz-OtZRFlBIx-VGJozUTW1ehUsGCHs_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
